### ISSUE TITLE
Security Issues With Custom Node

### ISSUE THREAD

**Issue by Kinglord** [avatechai/avatar-graph-comfyui#13]
Hi there,

I wanted to try out your custom node but I see that you require this to be configured
--enable-cors-header

Telling users to do this without explaining what they are doing is rather risky IMO. This isn't even mentioned in one of the install procedures which is even more concerning. There's nothing I can find that limits this access to your domain as well, which means that any code that knows how to talk to comfy via this header could hijack and control the user's local instance. Not trying to cast doubt, but the code for your editor also isn't open source as far as I can tell, so we have no idea what it's even capable of either.

I was looking forward to using this, especially to try and create content for us to use in Unity games, but given the current approach and lack of viz I'm not going to risk any of my development hardware on it and I hope everyone else understands the risks associated with this install.

**Comment by Radionic** [comment]
The --enable-cors-header is used to enable communication between ComfyUI and our editor ([https://editor.avatech.ai](https://editor.avatech.ai)), which is in charge of animating static characters. The only messages exchanged between them are the character data like the meshes of eyes and mouth, and the JSON format of our editor graph like below:

![Screenshot from 2023-11-08 12-24-34](https://github.com/avatechai/avatar-graph-comfyui/assets/52290138/e58061a7-136d-4f8c-bb60-a4c20e37aa28)

When you execute the ComfyUI graph, it sends the character data and the JSON graph to our editor. When you modify and save the graph in our editor, it sends the modified graph back to ComfyUI. To validate it, you can open the `js/index.js`, and log the message in `window.addEventListener("message", ...)` and `postMessage(message)`.

You can also run ComfyUI *without* the --enable-cors-header: execute the ComfyUI workflow, then download the .GLB or .GLTF format by right clicking the Avatar Main Output node and Save File option. Yet, this will disable the real-time character preview in the top-right corner of ComfyUI. Feel free to view it in other software like Blender.

We will add it to the README. Hope it helps address your concern.

**Comment by Kinglord** [comment]
Thank you for the detailed explanation and the update to the readme, including a workaround as well was excellent!
